# Generated by Django 4.0.dev20210830100804 on 2021-09-06 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_satellite', '0026_auto_20210906_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('satellite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_satellite.satellite')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_satellite.user')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('command', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('waterfall', models.TextField()),
                ('decoded', models.TextField()),
                ('processed', models.TextField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.command')),
                ('response_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.response')),
            ],
        ),
    ]
