# Generated by Django 3.2.6 on 2021-09-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_satellite', '0003_auto_20210906_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
