# Generated by Django 3.2.6 on 2021-09-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_satellite', '0012_auto_20210906_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='aop',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='ecc',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='inc',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='raan',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='sma',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='ta',
        ),
    ]
