# Generated by Django 3.2.6 on 2021-09-06 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_satellite', '0014_satellite_sma'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='inc',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-100000.0), django.core.validators.MaxValueValidator(100000.0)]),
        ),
        migrations.AddField(
            model_name='satellite',
            name='raan',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-100000.0), django.core.validators.MaxValueValidator(100000.0)]),
        ),
    ]
