# Generated by Django 3.2.6 on 2021-09-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_satellite', '0018_satellite_ta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='ta',
        ),
    ]
