# Generated by Django 3.2.6 on 2021-09-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_satellite', '0021_remove_satellite_tbugfix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='ta',
        ),
    ]
