# Generated by Django 3.2.6 on 2021-09-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_satellite', '0024_auto_20210906_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='true_anomaly',
            field=models.CharField(max_length=250),
        ),
    ]
