# Generated by Django 3.2.6 on 2021-09-06 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_satellite', '0025_alter_satellite_true_anomaly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='true_anomaly',
        ),
        migrations.AddField(
            model_name='satellite',
            name='ta',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-100000.0), django.core.validators.MaxValueValidator(100000.0)]),
        ),
    ]
